# Everforest Dark Hard
# Also add 'color_scheme = "everforest",' to your wezterm.lua file.
[colors]
foreground = "#d3c6aa"
background = "#2b3339"
cursor_bg = "#d3c6aa"
cursor_border = "#d3c6aa"
cursor_fg = "#2b3339"
selection_bg = "#d3c6aa"
selection_fg = "#2b3339"

ansi = ["#4b565c","#e67e80","#a7c080","#dbbc7f","#7fbbb3","#d699b6","#83c092","#d3c6aa"]
brights = ["#4b565c","#e67e80","#a7c080","#dbbc7f","#7fbbb3","#d699b6","#83c092","#d3c6aa"]
